{
  "openapi": "3.0.0",
  "info": {
    "title": "Team Task 2 - Binar Academy",
    "version": "1.0.0",
    "description": "API with CRUD Operation and Auth function. This API is made to fulfill the task from kak Imam.",
    "contact": {
      "name": "Team Task 2",
      "email": "teamtask@gmail.com",
      "url": "https://jayajayajaya.com"
    },
    "license": {
      "name": "MIT",
      "url": "https://github.com/ndikrp/team2-API-car-management/blob/main/LICENSE"
    }
  },
  "tags": [
    {
      "name": "Auths",
      "description": "API for resources auth"
    },
    {
      "name": "Cars",
      "description": "API for resources car"
    },
    {
      "name": "Rentals",
      "description": "API for resources rental"
    },
    {
      "name": "Details",
      "description": "API for resources detail"
    },
    {
      "name": "Users",
      "description": "API for resources user"
    }
  ],
  "servers": [
    {
      "description": "Car Management API",
      "url": "http://localhost:8000/api/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/auth/login": {
      "post": {
        "tags": ["Auths"],
        "summary": "Return the results from hit API login user",
        "description": " API for login user",
        "requestBody": {
          "description": "request body for succes login user",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "hafiedz@mail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "admin"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success User login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "message": {
                      "type": "string",
                      "example": "Berhasil login"
                    },
                    "data": {
                      "type": "string",
                      "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYWRobGFuIiwicm9sZSI6IlN1cGVyYWRtaW4iLCJlbWFpbCI6ImZhZGhsYW5AZ21haWwuY29tIiwiaWF0IjoxNjk3OTM5ODMwfQ.hBED_9F3gLAwACOv7uOIeHR_6yKwQBwkf8WIVuEVQzs"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "wrong password or user not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "wrong password or user not found"
                    }
                  }
                }
              }
            }
          },
          "405": {
            "description": "Email format error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "Invalid email format"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "tags": ["Auths"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Return the results from hit API register user",
        "description": " API for register user",
        "requestBody": {
          "description": " request body for success register user",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "rend"
                  },
                  "email": {
                    "type": "string",
                    "example": "rend@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "rend123"
                  },
                  "confirmPassword": {
                    "type": "string",
                    "example": "rend123"
                  },
                  "age": {
                    "type": "integer",
                    "example": 20
                  },
                  "address": {
                    "type": "string",
                    "example": "Nusantara"
                  },
                  "role": {
                    "type": "string",
                    "example": "Manager"
                  },
                  "rentalId": {
                    "type": "integer",
                    "example": 2
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success register",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "dataValues": {
                          "id": 72,
                          "name": "rend",
                          "address": "Nusantara",
                          "age": 20,
                          "rentalId": 2,
                          "role": "Manager",
                          "updatedAt": "2024-04-25T09:41:53.042Z",
                          "createdAt": "2024-04-25T09:41:53.042Z",
                          "image": null
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "Token not found!"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "No Access",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "Staff is not allowed to register new users"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Email already taken",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "User email already taken"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/me": {
      "get": {
        "tags": ["Auths"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Return the results from hit API checktoken user",
        "description": " API for checktoken user",
        "responses": {
          "200": {
            "description": "Succes checktoken",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "user": {
                          "id": 1,
                          "name": "Hafiedz",
                          "age": 20,
                          "address": "Indonesia",
                          "image": "gambar1.png",
                          "role": "Admin",
                          "rentalId": null,
                          "createdAt": "2024-04-18T13:24:53.050Z",
                          "updatedAt": "2024-04-18T13:24:53.050Z",
                          "Auth": {
                            "id": 1,
                            "email": "hafiedz@mail.com",
                            "password": "$2a$12$52jmU1ASdJaCPNaZyCPIKOaiQV/3Ms7A41qv7lgZ2PMc2gCuOdWbe",
                            "userId": 1,
                            "createdAt": "2024-04-18T13:24:53.076Z",
                            "updatedAt": "2024-04-18T13:24:53.076Z"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "Token not found!"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Token expired",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Token Expired"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/rentals": {
      "get": {
        "tags": ["Rentals"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Melihat semua data yang ada di resource rental",
        "description": "Melihat semua data yang ada di resource rental",
        "responses": {
          "200": {
            "description": "Success Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "totalData": {
                      "type": "number",
                      "example": 2
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "rentals": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "name": {
                                "type": "string"
                              },
                              "city": {
                                "type": "string"
                              },
                              "createdAt": {
                                "type": "string"
                              },
                              "updatedAt": {
                                "type": "string"
                              }
                            }
                          },
                          "example": [
                            {
                              "id": 1,
                              "name": "Rental Rafli",
                              "city": "Makassar",
                              "createdAt": "2024-04-19T13:24:52.028Z",
                              "updatedAt": "2024-04-19T13:24:52.028Z"
                            },
                            {
                              "id": 2,
                              "name": "Rental Rendi",
                              "city": "Makassar",
                              "createdAt": "2024-04-19T13:24:52.028Z",
                              "updatedAt": "2024-04-19T13:24:52.028Z"
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "No Access / No Token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "Token not found!"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "JWT Malformed (Token tidak valid / tidak sesuai dengan format JWT)",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "jwt malformed"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/rental/{id}": {
      "get": {
        "tags": ["Rentals"],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "summary": "Melihat data rental berdasarkan id pada resource rental",
        "description": "Melihat data rental berdasarkan id pada resource rental",
        "responses": {
          "200": {
            "description": "Success Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "rental": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "number",
                              "example": 2
                            },
                            "name": {
                              "type": "string",
                              "example": "Rental Rendi"
                            },
                            "city": {
                              "type": "string",
                              "example": "Makassar"
                            },
                            "createdAt": {
                              "type": "string",
                              "example": "2024-04-19T13:24:52.028Z"
                            },
                            "updatedAt": {
                              "type": "string",
                              "example": "2024-04-19T13:24:52.028Z"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "No Access / No Token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "Token not found!"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "JWT Malformed (Token tidak valid / tidak sesuai dengan format JWT)",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "jwt malformed"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["Rentals"],
        "security": [
          {
            "bearerAuth ": []
          }
        ],
        "summary": "Mengupdate data rental berdasarkan id",
        "description": "Mengupdate data rental berdasarkan id",
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Nama rental"
                  },
                  "city": {
                    "type": "string",
                    "description": "Kota rental"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "number",
              "example": 1
            },
            "description": "rental id"
          }
        ],
        "responses": {
          "200": {
            "description": "Success Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "updatedRental": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "number",
                              "example": 2
                            },
                            "name": {
                              "type": "string",
                              "example": "Rafli Rental"
                            },
                            "city": {
                              "type": "string",
                              "example": "Makassar"
                            },
                            "createdAt": {
                              "type": "string",
                              "example": "2024-04-19T13:24:52.028Z"
                            },
                            "updatedAt": {
                              "type": "string",
                              "example": "2024-04-19T13:24:52.028Z"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "No Access",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "message": {
                      "type": "string",
                      "example": "Akses anda tidak diterima. Role yang memiliki akses : Admin atau Manager"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "No Request Body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Silahkan input data yang mau diubah"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
